name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - name: Build release
        run: cargo build --release

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: target/release/cc-swap.exe
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'a') || contains(github.ref, 'b') || contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
