name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: target/release/cc-swap
            arch: x86_64-linux
            ext: ""
            dep_cmd: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxkbcommon-dev libfontconfig1-dev
          - os: windows-latest
            artifact: target/release/cc-swap.exe
            arch: x86_64-windows
            ext: .exe
            dep_cmd: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - name: Install system deps
        if: matrix.dep_cmd != ''
        run: ${{ matrix.dep_cmd }}

      - name: Build release
        run: cargo build --release

      - name: Rename artifact
        shell: bash
        run: mv ${{ matrix.artifact }} cc-swap-${{ github.ref_name }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: cc-swap-${{ matrix.os }}
          path: cc-swap-${{ github.ref_name }}-${{ matrix.arch }}${{ matrix.ext }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            cc-swap-ubuntu-latest/cc-swap-${{ github.ref_name }}-x86_64-linux
            cc-swap-windows-latest/cc-swap-${{ github.ref_name }}-x86_64-windows.exe
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'pre') || contains(github.ref_name, 'rc') }}
